language: ruby
rvm:
  - 2.6.3
before_install:
  - curl -O https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.2.1-amd64.deb && sudo dpkg -i --force-confnew elasticsearch-7.2.1.deb && sudo service elasticsearch restart
services:
  - elasticsearch
cache: bundler
script:
  - bundle exec rspec