language: ruby
rvm:
  - 2.5.3

before_install:
- curl -O https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.2.1-amd64.deb && sudo dpkg -i --force-confnew elasticsearch-7.2.1-amd64.deb
- sudo service elasticsearch start
- java --version

cache: bundler

before_script:
  - sleep 10

script:
  - curl -v http://localhost:9200/
  - bundle exec rspec