language: ruby
rvm:
  - 2.5.3

before_install:
- curl -O https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.2.1-amd64.deb
- sudo dpkg -i --force-confnew elasticsearch-7.2.1-amd64.deb
- sudo chown -R elasticsearch:elasticsearch /etc/default/elasticsearch
- sudo -i service elasticsearch restart

cache: bundler

before_script:
  - sleep 10

script:
  - curl localhost:9200
  - bundle exec rspec