language: ruby
rvm:
  - 2.5.3
jdk:
  - oraclejdk14

env:
  global:
    - TEST_ES_SERVER=http://localhost:9250
    - ELASTICSEARCH_VERSION=7.2.0

before_install:
- curl -O https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.2.1-amd64.deb && sudo dpkg -i --force-confnew elasticsearch-7.2.1-amd64.deb
- sudo service elasticsearch start

cache: bundler

before_script:
  - sleep 10

script:
  - curl -v http://localhost:9250/
  - curl -v http://localhost:9200/
  - bundle exec rspec