sudo: required
language: ruby
rvm:
  - 2.5.3

env:
  global:
    - TEST_ES_SERVER=http://localhost:9200
    - ELASTICSEARCH_VERSION=7.2.1

before_install:
- pkill -9 -f elasticsearch || true
- curl https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-${ELASTICSEARCH_VERSION}-linux-x86_64.tar.gz | tar xz -C /tmp
- /tmp/elasticsearch-${ELASTICSEARCH_VERSION}/bin/elasticsearch-keystore create
- /tmp/elasticsearch-${ELASTICSEARCH_VERSION}/bin/elasticsearch

cache: bundler

before_script:
  - sleep 20

script:
  - curl -v ${TEST_ES_SERVER}
  - bundle exec rspec